### ISSUE TITLE
ghc-8.6 - SyntaxError: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by ddssff** [ghcjs/ghcjs#725]
I'm getting the following from a  module that has some template haskell.  This is with a compiler built with the latest everything as of 1/1/2019.

```
uncaught exception in Haskell main thread: SyntaxError: Invalid regular expression: missing /
  SyntaxError: Invalid regular expression: missing /
         at eval (<anonymous>)
         at Object.h$loadCodeStr [as loadCodeStr] (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:177:10)
         at Object.h$loadCode [as loadCode] (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:185:10)
         at h$$ghcjszmthzm0zi1zi0zi0zm7BCoOUH0brA9lsyasf3SuUZCGHCJSziPrimziTHziEval_fQ (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:177:10), <anonymous>:96315:16)
         at h$runThreadSlice (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:177:10), <anonymous>:6779:11)
         at h$runThreadSliceCatch (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:177:10), <anonymous>:6747:12)
         at h$mainLoop (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:177:10), <anonymous>:6742:9)
         at eval (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:177:10), <anonymous>:7228:13)
         at /usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:133:9
         at h$processQueue (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190101/ghcjs/thrunner.js:109:13)
```

**Comment by ddssff** [comment]
This is on ubuntu bionic.

**Comment by luite** [comment]
Hmm that sounds like an encoding problem. Can you post the code to
reproduce this?

**Comment by ddssff** [comment]
I will but it will be a while.

**Comment by ddssff** [comment]
Its one of those things where you simplify, simplify simplify and suddenly the error goes away, but when you go back a step it doesn't come back.

**Comment by ddssff** [comment]
That syntax error message comes from nodejs-8.10.0.  Is there any reason to fiddle with nodejs versions?

**Comment by ddssff** [comment]
maybe I should try to isolate which ghcjs patch caused it.

**Comment by ddssff** [comment]
I'm missing the days when ghc would compile the modules in the same order each time and stop when there was an error.

**Comment by ddssff** [comment]
Ok, here it is.  Requires safecopy and ghcjs-jquery packages.  It might be some problem in our ghcjs-jquery package, I will look into that next.  Compile this with `ghcjs -outputdir dist Main.hs` and see if you get the compiler crash I am seeing.

```
{-# LANGUAGE TemplateHaskell #-}

import Data.SafeCopy (base, deriveSafeCopy)
import JavaScript.JQuery () -- <- causes failure

data LayoutStyle = LS_Bootstrap | LS_Flexbox | LS_CustomCSS

$(deriveSafeCopy 1 'base ''LayoutStyle)

main :: IO ()
main = putStrLn "Hello"
```

My output:

```
$ rm -rf dist && ghcjs -outputdir dist Main.hs
[1 of 1] Compiling Main             ( Main.hs, dist/Main.js_o )
Linking Template Haskell (ThRunner1)
uncaught exception in Haskell main thread: SyntaxError: Invalid regular expression: missing /
SyntaxError: Invalid regular expression: missing /
    at eval (<anonymous>)
    at Object.h$loadCodeStr [as loadCodeStr] (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:177:10)
    at Object.h$loadCode [as loadCode] (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:185:10)
    at h$$ghcjszmthzm0zi1zi0zi0zm2QqVvRFJCKKBQwSEOkOWlxZCGHCJSziPrimziTHziEval_fQ (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:177:10), <anonymous>:96315:16)
    at h$runThreadSlice (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:177:10), <anonymous>:6771:11)
    at h$runThreadSliceCatch (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:177:10), <anonymous>:6747:12)
    at h$mainLoop (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:177:10), <anonymous>:6742:9)
    at eval (eval at h$loadCodeStr (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:177:10), <anonymous>:7228:13)
    at /usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:133:9
    at h$processQueue (/usr/lib/ghcjs/.ghcjs/x86_64-linux-8.6.0.1-8.6.2.20190107/ghcjs/thrunner.js:109:13)
Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.6.0:Data.Binary.Get
```

**Comment by ddssff** [comment]
Here is the ghcjs-jquery repository we are using: `https://github.com/seereason/ghcjs-jquery`

**Comment by ddssff** [comment]
It only fails if ghcjs-jquery is installed as a package, if you compile the modules into the executable it succeeds.

**Comment by cdsmith** [comment]
Why did you close the issue?  It sounds like this is still broken to me.

**Comment by ddssff** [comment]
I hit the wrong comment button, sorry.

**Comment by luite** [comment]
the line
```
        rprotocol = /^\/\//,
```

from the jquery source gets mangled somehow. it's still stored correctly in the `js_a` archive. I suspect the preprocessor mangles it, by stripping the "comment"

That also explains the missing closure compiler annotations seen by @Mikolaj

**Comment by luite** [comment]
this should be fixed by 87038f12be6e896ee80239122d87e6ddd64fa55e

**Comment by ddssff** [comment]
This patch was reverted - is this still an issue?  Is there a fix or a workaround?

(Answering self - a good workaround is to modify the code that causes the bug.  In my case it was a template haskell macro that I managed to remove.)

**Comment by Mikolaj** [comment]
It might be fixed by #741.

**Comment by ddssff** [comment]
I'm still getting this with the latest ghcjs-8.6, which includes this patch as commit 91d36ca.

**Comment by ddssff** [comment]
I've got a very simple example that triggers this bug, if you've installed the th-lift package:
```
import Language.Haskell.TH.Lift (deriveLift)
import Language.Haskell.TH.Syntax (Loc)

$(deriveLift ''Loc)
```
or this:
```
import Language.Haskell.TH.Instances ({-instance Lift Loc-})
import Language.Haskell.TH.Lift (lift)
import Language.Haskell.TH.Syntax (Loc, location)

bug :: Loc
bug = $(lift =<< location)
```

**Comment by ddssff** [comment]
dumb close and comment button.

**Comment by Mikolaj** [comment]
Seriously, dear people, you possibly have a fix ready for months, the one I mentioned above, but you don't even deign to verify. Please do. :)

**Comment by ddssff** [comment]
ok here goes

**Comment by ddssff** [comment]
To be fair to myself, until now testing for this bug has been a big production.

**Comment by ddssff** [comment]
Unfortunately, your patch does not seem to resolve the issue.  (sad emoji)

**Comment by Mikolaj** [comment]
Oh well, good to know. :) Thank you for it trying out. Actually, I probably mixed up issues and I was exasperated that nobody tried if it fixes https://github.com/ghcjs/ghcjs/issues/735.

**Comment by ddssff** [comment]
We might change `rprotocol = /^\/\//,` to `rprotocol = /^\/{2}/,` in jquery.   Or `/^[\/][\/]/`, or something.

**Comment by ddssff** [comment]
I have made this change and all the SyntaxError issues go away.

**Comment by Mikolaj** [comment]
Congrats! Which change precisely (you mentioned two)?

**Comment by ddssff** [comment]
The {2} version worked, did not try the other.  Ultimately we discovered that jquery was being included in our lib.js by mistake, and we removed it.
